name: Componizer CI
env:
  NODE_VERSION: "12.x"

on:
  push:
    branches:
      - master

jobs:
  build_extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1      
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install and Test
        working-directory: ./extension
        run: npm install
      - name: Package artifact
        working-directory: ./extension
        run: npm run package
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: componizer.vsix
          path: ./extension/componizer-0.0.1.vsix

  build_schematics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install and Test
        working-directory: ./schematics
        run: npm install && npm test

      - name: Package artifacts
        working-directory: ./schematics
        run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: componizer-schematics
          path: ./schematics/dist

  publish_artifacts:
    runs-on: ubuntu-latest
    needs: [build_extension, build_schematics]
    steps:
      - name: Download schematics artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: componizer-schematics
      - name: Download extension artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: componizer.vsix
      - name: Publish extension
        uses: JCofman/vscodeaction@master
        with:
          args: publish --packagePath componizer.vsix -p ${{ secrets.VSCE_PUB_TOKEN }}
      - name: Publish schematics
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}
          npm publish componizer-schematics     
